// Code generated by "stringer -type=Instruction"; DO NOT EDIT.

package computer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LDA_I-169]
	_ = x[LDA_Z-165]
	_ = x[LDX_I-162]
	_ = x[STA_Z-133]
	_ = x[ADC_Z-101]
	_ = x[ADC_ZX-117]
	_ = x[ASL_A-10]
	_ = x[CLC-24]
	_ = x[RTS-96]
	_ = x[JMP_ABS-76]
	_ = x[JMP_IND-108]
}

const _Instruction_name = "ASL_ACLCJMP_ABSRTSADC_ZJMP_INDADC_ZXSTA_ZLDX_ILDA_ZLDA_I"

var _Instruction_map = map[Instruction]string{
	10:  _Instruction_name[0:5],
	24:  _Instruction_name[5:8],
	76:  _Instruction_name[8:15],
	96:  _Instruction_name[15:18],
	101: _Instruction_name[18:23],
	108: _Instruction_name[23:30],
	117: _Instruction_name[30:36],
	133: _Instruction_name[36:41],
	162: _Instruction_name[41:46],
	165: _Instruction_name[46:51],
	169: _Instruction_name[51:56],
}

func (i Instruction) String() string {
	if str, ok := _Instruction_map[i]; ok {
		return str
	}
	return "Instruction(" + strconv.FormatInt(int64(i), 10) + ")"
}
